const feedbackComments = [

"Excellent service.",
"Very polite staff.",
"Medicine was available.",
"Fast service.",
"Good behaviour.",
"Affordable prices.",
"Clean medical store.",
"Highly recommended.",
"Quick response.",
"Very satisfied.",
"Professional staff.",
"Helpful pharmacist.",
"Good experience.",
"Best medical store.",
"Nice environment.",
"Medicine quality is good.",
"Everything was available.",
"Very cooperative.",
"Fast billing.",
"Trusted medical shop.",
"Friendly service.",
"Easy to find medicines.",
"Excellent support.",
"Very impressed.",
"Always reliable.",
"Quick delivery.",
"Good customer care.",
"Satisfied with service.",
"Very genuine.",
"Helpful and caring.",
  "Good stock availability.",
"Very quick service.",
"Reasonable prices.",
"Excellent customer support.",
"Staff is very helpful.",
"Medicines were available.",
"Very clean store.",
"Highly satisfied.",
"Very fast billing.",
"Nice experience.",
"Excellent behaviour.",
"Friendly atmosphere.",
"Very professional.",
"Highly trusted.",
"Good quality medicines.",
"Always available.",
"Very cooperative staff.",
"Good guidance.",
"Best service nearby.",
"Satisfied customer.",
"Quick medicine delivery.",
"Nice management.",
"Helpful owner.",
"Everything was organized.",
"Affordable medicines.",
"Fast response.",
"Great customer care.",
"Very reliable.",
"Wonderful experience.",
"Excellent pharmacy.",
"Good communication.",
"Medicine received on time.",
"Very genuine products.",
"Store is well maintained.",
"Happy with the service.",
"Staff explained everything well.",
"Always my first choice.",
"Prompt support.",
"Very efficient.",
"Excellent medicine availability.",
"Nice staff.",
"Trusted medical store.",
"Good location.",
"Very convenient.",
"Polite behaviour.",
"Excellent assistance.",
"Best experience.",
"Very good service.",
"Highly appreciated.",
"Will visit again.",
  "Good packaging.",
"Fast checkout.",
"Very supportive staff.",
"Helpful suggestions.",
"Best pharmacy experience.",
"Good hygiene.",
"Excellent inventory.",
"Very responsive.",
"Medicine found easily.",
"Happy customer.",
"Professional guidance.",
"Highly dependable.",
"Very organized store.",
"Quick assistance.",
"Satisfied every time.",
"Great medicine collection.",
"Excellent customer handling.",
"Very smooth process.",
"Neat and clean shop.",
"Always a pleasant visit.",
"Good service quality.",
"Friendly pharmacist.",
"Excellent staff behaviour.",
"Very honest service.",
"Great shopping experience.",
"Affordable and genuine.",
"Reliable medicine store.",
"Very comfortable experience.",
"Quick and easy purchase.",
"Best customer support.",
"Very impressed with service.",
"Medicine always available.",
"Nice discount offers.",
"Very caring staff.",
"Fast prescription service.",
"Excellent overall experience.",
"Highly recommended pharmacy.",
"Good value for money.",
"Very satisfied with staff.",
"Keep up the good work."

];
